name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  mask_text_input_formatter: ^2.8.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  http: ^1.2.0
  lazy_load_scrollview: ^1.3.0
  badges: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/CloudsSeason.jpg
    - assets/rainySeason.jpg
    - assets/SnowySeason.jpg
